<?php

namespace Dbvc\AiPackage;

if (! defined('WPINC')) {
    die;
}

final class PackageDocBuilder
{
    /**
     * @param array<string,mixed> $context
     * @param array<int,string>   $included_docs
     * @return array<string,string>
     */
    public static function build_root_docs(array $context, array $included_docs): array
    {
        $included_docs = array_values(array_unique(array_filter(array_map('sanitize_key', $included_docs))));
        $docs = [];

        foreach ($included_docs as $doc_key) {
            switch ($doc_key) {
                case 'readme':
                    $docs['README.md'] = self::build_readme($context);
                    break;
                case 'agents':
                    $docs['AGENTS.md'] = self::build_agents_doc($context);
                    break;
                case 'starter_prompt':
                    $docs['STARTER_PROMPT.md'] = self::build_starter_prompt($context);
                    break;
                case 'output_contract':
                    $docs['OUTPUT_CONTRACT.md'] = self::build_output_contract($context);
                    break;
                case 'user_rules':
                    $docs['USER_RULES.md'] = self::build_user_rules_doc($context);
                    break;
                case 'validation_rules':
                    $docs['VALIDATION_RULES.md'] = self::build_validation_rules_doc($context);
                    break;
            }
        }

        return $docs;
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_readme(array $context): string
    {
        $site_name = self::get_site_name($context);
        $home_url = self::get_home_url($context);
        $summary = self::build_summary_lines($context);

        $lines = [
            '# DBVC AI Sample Package',
            '',
            'This archive was generated by DBVC for the current site so an AI system can understand the expected content shapes before drafting new entities or updates.',
            '',
            '## Site',
            '',
            '- Site: `' . $site_name . '`',
            '- Origin: `' . $home_url . '`',
            '- Site fingerprint: `' . self::get_site_fingerprint($context) . '`',
            '',
            '## Quick Start',
            '',
            '1. Upload this ZIP to your AI session.',
            '2. Paste the prompt from `STARTER_PROMPT.md`.',
            '3. Ask the AI to return a strict `dbvc_ai_submission_package` ZIP.',
            '4. Upload that returned ZIP into DBVC.',
            '',
            '## Package Summary',
            '',
        ];

        foreach ($summary as $line) {
            $lines[] = '- ' . $line;
        }

        $lines[] = '';
        $lines[] = '## Included Artifacts';
        $lines[] = '';
        $lines[] = '- `schema/object-inventory.json` describes the selected object types.';
        $lines[] = '- `schema/field-catalog.json` lists core, registered meta, observed meta, taxonomy, and ACF field context.';
        $lines[] = '- `schema/validation-rules.json` describes the current DBVC validation contract.';
        $lines[] = '- `samples/` contains canonical sample JSON plus sibling markdown guidance for each selected object type.';
        $lines[] = '';
        $lines[] = 'Use the sample JSON as the source of truth for output shape. Use the markdown docs to understand rules, allowed values, and authoring guidance.';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_agents_doc(array $context): string
    {
        $selection = self::get_selection($context);
        $post_types = ! empty($selection['post_types']) ? implode('`, `', array_map('strval', $selection['post_types'])) : 'none';
        $taxonomies = ! empty($selection['taxonomies']) ? implode('`, `', array_map('strval', $selection['taxonomies'])) : 'none';
        $variants = self::get_variants($context);

        $lines = [
            '# AGENTS',
            '',
            'Follow these rules when using this package to author a DBVC AI submission package.',
            '',
            '## Scope',
            '',
            '- Selected post types: `' . $post_types . '`',
            '- Selected taxonomies: `' . $taxonomies . '`',
            '- Included variants: `' . implode('`, `', array_map('strval', $variants)) . '`',
            '',
            '## Rules',
            '',
            '- Treat the JSON files in `samples/` as the canonical output shape.',
            '- Preserve top-level field names exactly as shown in the sample JSON.',
            '- Use `ID: 0` or `term_id: 0` for net-new entities.',
            '- Do not invent top-level `vf_object_uid` for net-new entities.',
            '- Prefer slug-based references over numeric IDs.',
            '- Do not invent DBVC bookkeeping meta or ACF underscore reference keys.',
            '- Supported first-pass ACF relationship families are `post_object`, `relationship`, and `taxonomy` when authored with slug-based refs.',
            '- Keep media-like fields neutral unless the package explicitly instructs otherwise. Non-empty media-like values are blocked in v1.',
            '',
            '## Expected Return',
            '',
            '- Return a ZIP with a root `dbvc-ai-manifest.json`.',
            '- Put post entities in `entities/posts/{post_type}/{slug}.json`.',
            '- Put term entities in `entities/terms/{taxonomy}/{slug}.json`.',
            '- Match the current site fingerprint unless you are explicitly told to target a different site.',
            '',
            '## Working Method',
            '',
            '- Read `README.md`, `OUTPUT_CONTRACT.md`, and `VALIDATION_RULES.md` before authoring output.',
            '- Read the sibling `.md` file beside each sample JSON you use.',
            '- If a field is unclear, preserve the key and use a conservative placeholder rather than inventing unsupported structure.',
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_starter_prompt(array $context): string
    {
        $settings = Settings::get_all_settings();
        $guidance = isset($settings['guidance']) && is_array($settings['guidance']) ? $settings['guidance'] : [];
        $template = trim((string) ($guidance['starter_prompt_template'] ?? ''));
        if ($template !== '') {
            return $template . "\n";
        }

        $selection = self::get_selection($context);
        $post_types = ! empty($selection['post_types']) ? implode(', ', array_map('strval', $selection['post_types'])) : 'none';
        $taxonomies = ! empty($selection['taxonomies']) ? implode(', ', array_map('strval', $selection['taxonomies'])) : 'none';

        $lines = [
            'Use the attached DBVC AI sample package to understand the exact JSON shapes required for this site.',
            '',
            'Requirements:',
            '- Read the root docs and the sibling `.md` files beside any sample JSON you use.',
            '- Return a ZIP file whose root contains `dbvc-ai-manifest.json`.',
            '- Place post entities in `entities/posts/{post_type}/{slug}.json`.',
            '- Place term entities in `entities/terms/{taxonomy}/{slug}.json`.',
            '- Mirror the canonical DBVC-shaped sample JSON exactly.',
            '- Use `ID: 0` or `term_id: 0` for new entities unless an update target is explicitly provided.',
            '- Prefer slug-based references instead of numeric IDs.',
            '- Do not invent DBVC bookkeeping fields, history hashes, or ACF underscore keys.',
            '- Keep unsupported complex ACF families empty unless the sample JSON and sibling docs explicitly show a supported structure.',
            '',
            'Current selected scope:',
            '- Post types: ' . $post_types,
            '- Taxonomies: ' . $taxonomies,
            '',
            'Return only the finished package contents needed for DBVC import, using the contract described in `OUTPUT_CONTRACT.md`.',
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_output_contract(array $context): string
    {
        $variants = self::get_variants($context);
        $lines = [
            '# Output Contract',
            '',
            'Return a strict `dbvc_ai_submission_package` ZIP.',
            '',
            '## Required Layout',
            '',
            '```text',
            'dbvc-ai-manifest.json',
            'entities/posts/{post_type}/{entity-slug}.json',
            'entities/terms/{taxonomy}/{term-slug}.json',
            'docs/NOTES.md',
            'reports/generation-summary.md',
            '```',
            '',
            '## Manifest Minimum',
            '',
            'The returned root manifest must include:',
            '',
            '- `package_type: "dbvc_ai_submission_package"`',
            '- `package_schema_version: 1`',
            '- `generated_at`',
            '- `source_sample_package.site_fingerprint`',
            '- `source_sample_package.package_schema_version`',
            '- `intended_operation`',
            '- `counts`',
            '',
            '## Entity Rules',
            '',
            '- Mirror the sample JSON field names exactly.',
            '- Use one file per entity.',
            '- Use slug-based filenames that match the entity slug.',
            '- Keep updates and creates in the same package only when each entity is unambiguous.',
            '- Preserve `ID: 0` and `term_id: 0` for create-intent entities.',
            '- Only include `vf_object_uid` when the target update identity is known.',
            '- Non-empty unsupported complex or media-centric ACF values are blocked in v1.',
            '',
            '## Package Context',
            '',
            '- Sample variants included here: `' . implode('`, `', array_map('strval', $variants)) . '`',
            '- Site fingerprint: `' . self::get_site_fingerprint($context) . '`',
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_user_rules_doc(array $context): string
    {
        $settings = Settings::get_all_settings();
        $guidance = isset($settings['guidance']) && is_array($settings['guidance']) ? $settings['guidance'] : [];
        $rules = isset($settings['rules']) && is_array($settings['rules']) ? $settings['rules'] : [];

        $lines = [
            '# User Rules',
            '',
            'This document exports the current DBVC AI guidance and structured rule defaults.',
            '',
        ];

        $global_ai_guidance = trim((string) ($guidance['global_ai_guidance'] ?? ''));
        if ($global_ai_guidance !== '') {
            $lines[] = '## Global AI Guidance';
            $lines[] = '';
            $lines[] = $global_ai_guidance;
            $lines[] = '';
        }

        $global_notes = trim((string) ($guidance['global_notes_markdown'] ?? ''));
        if ($global_notes !== '') {
            $lines[] = '## Global Notes';
            $lines[] = '';
            $lines[] = $global_notes;
            $lines[] = '';
        }

        $lines[] = '## Structured Rules';
        $lines[] = '';
        $lines[] = '```json';
        $lines[] = (string) wp_json_encode($rules, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $lines[] = '```';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function build_validation_rules_doc(array $context): string
    {
        $rules = isset($context['validation_rules']) && is_array($context['validation_rules']) ? $context['validation_rules'] : [];
        $states = isset($rules['states']) && is_array($rules['states']) ? $rules['states'] : [];
        $validation_defaults = isset($rules['validation_defaults']) && is_array($rules['validation_defaults']) ? $rules['validation_defaults'] : [];

        $lines = [
            '# Validation Rules',
            '',
            'DBVC will validate future AI submission packages against the current rule contract before importer handoff.',
            '',
            '## Validation Defaults',
            '',
        ];

        foreach ($validation_defaults as $key => $value) {
            $lines[] = '- `' . (string) $key . '`: `' . (string) $value . '`';
        }

        $lines[] = '';
        $lines[] = '## Validation States';
        $lines[] = '';

        foreach ($states as $state => $description) {
            $lines[] = '- `' . (string) $state . '`: ' . (string) $description;
        }

        $lines[] = '';
        $lines[] = '## Current Contract Snapshot';
        $lines[] = '';
        $lines[] = '```json';
        $lines[] = (string) wp_json_encode($rules, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $lines[] = '```';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $context
     * @return array<int,string>
     */
    private static function build_summary_lines(array $context): array
    {
        $selection = self::get_selection($context);
        $counts = isset($context['counts']) && is_array($context['counts']) ? $context['counts'] : [];
        $variants = self::get_variants($context);

        return [
            'Post types in scope: ' . count((array) ($selection['post_types'] ?? [])),
            'Taxonomies in scope: ' . count((array) ($selection['taxonomies'] ?? [])),
            'Sample JSON files: ' . (int) ($counts['sample_json_files'] ?? 0),
            'Sample markdown files: ' . (int) ($counts['sample_markdown_files'] ?? 0),
            'Root docs: ' . (int) ($counts['root_doc_files'] ?? 0),
            'Included variants: `' . implode('`, `', array_map('strval', $variants)) . '`',
        ];
    }

    /**
     * @param array<string,mixed> $context
     * @return array<string,mixed>
     */
    private static function get_selection(array $context): array
    {
        return isset($context['selection']) && is_array($context['selection']) ? $context['selection'] : ['post_types' => [], 'taxonomies' => []];
    }

    /**
     * @param array<string,mixed> $context
     * @return array<int,string>
     */
    private static function get_variants(array $context): array
    {
        $variants = isset($context['variants']) && is_array($context['variants']) ? array_map('strval', $context['variants']) : [];
        if (empty($variants)) {
            $variants = ['single'];
        }

        return $variants;
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function get_site_name(array $context): string
    {
        return isset($context['site_origin']['name']) ? (string) $context['site_origin']['name'] : (string) get_bloginfo('name');
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function get_home_url(array $context): string
    {
        return isset($context['site_origin']['home_url']) ? (string) $context['site_origin']['home_url'] : trailingslashit(home_url('/'));
    }

    /**
     * @param array<string,mixed> $context
     * @return string
     */
    private static function get_site_fingerprint(array $context): string
    {
        return isset($context['site_fingerprint']) ? (string) $context['site_fingerprint'] : '';
    }
}
